kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: rm-343686-hvsilva
  selfLink: /apis/project.openshift.io/v1/projects/rm-343686-hvsilva
  uid: aaeb6a98-eea1-47a0-945c-0cd76c61dbbd
  resourceVersion: '90550027'
  creationTimestamp: '2022-07-05T21:35:09Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: vogqqq
    openshift.io/sa.scc.mcs: 's0:c62,c49'
    openshift.io/sa.scc.supplemental-groups: 1003880000/10000
    openshift.io/sa.scc.uid-range: 1003880000/10000
  managedFields:
    - manager: cluster-policy-controller
      operation: Update
      apiVersion: v1
      time: '2022-07-05T21:35:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: v1
      time: '2022-07-05T21:35:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
        'f:status':
          'f:phase': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-07-05T21:35:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
